# Shell variables
# Generated by 'wal'
wallpaper="/home/mkrol/Pictures/i3wallpapers/main.png"

# Special
background='#0b2327'
foreground='#c2c8c9'
cursor='#c2c8c9'

# Colors
color0='#0b2327'
color1='#3ab3c5'
color2='#19a7c6'
color3='#0d8db4'
color4='#0277aa'
color5='#1574aa'
color6='#0764aa'
color7='#c2c8c9'
color8='#485a5d'
color9='#3ab3c5'
color10='#19a7c6'
color11='#0d8db4'
color12='#0277aa'
color13='#1574aa'
color14='#0764aa'
color15='#c2c8c9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
