--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mkrol/Pictures/i3wallpapers/main.png"

-- Special
background="#0b2327"
foreground="#c2c8c9"
cursor="#c2c8c9"

-- Colors
color0="#0b2327"
color1="#3ab3c5"
color2="#19a7c6"
color3="#0d8db4"
color4="#0277aa"
color5="#1574aa"
color6="#0764aa"
color7="#c2c8c9"
color8="#485a5d"
color9="#3ab3c5"
color10="#19a7c6"
color11="#0d8db4"
color12="#0277aa"
color13="#1574aa"
color14="#0764aa"
color15="#c2c8c9"
