--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mkrol/Pictues/i3wmwallpapers/main.jpg"

-- Special
background="#141021"
foreground="#c4c3c7"
cursor="#c4c3c7"

-- Colors
color0="#141021"
color1="#6554aa"
color2="#8766aa"
color3="#a093a6"
color4="#a96395"
color5="#ac3b63"
color6="#b46b7e"
color7="#c4c3c7"
color8="#4e4b58"
color9="#6554aa"
color10="#8766aa"
color11="#a093a6"
color12="#a96395"
color13="#ac3b63"
color14="#b46b7e"
color15="#c4c3c7"
