# Shell variables
# Generated by 'wal'
wallpaper='/home/mkrol/Pictues/i3wmwallpapers/main.jpg'

# Special
background='#141021'
foreground='#c4c3c7'
cursor='#c4c3c7'

# Colors
color0='#141021'
color1='#6554aa'
color2='#8766aa'
color3='#a093a6'
color4='#a96395'
color5='#ac3b63'
color6='#b46b7e'
color7='#c4c3c7'
color8='#4e4b58'
color9='#6554aa'
color10='#8766aa'
color11='#a093a6'
color12='#a96395'
color13='#ac3b63'
color14='#b46b7e'
color15='#c4c3c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
